Case Study 2/HRWebApp/HRWebApp/Models/Job_History.cs
namespace HRWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Job_History
    {
        [Column(TypeName = "numeric")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public decimal ID { get; set; }

        [Column(TypeName = "numeric")]
        public decimal Employee_ID { get; set; }

        [StringLength(50)]
        public string Department { get; set; }

        [StringLength(50)]
        public string Division { get; set; }

        public DateTime? Start_Date { get; set; }

        public DateTime? End_Date { get; set; }

        [StringLength(50)]
        public string Job_Title { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? Supervisor { get; set; }

        [StringLength(50)]
        public string Job_Category { get; set; }

        [StringLength(50)]
        public string Location { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? Departmen_Code { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? Salary_Type { get; set; }

        [StringLength(50)]
        public string Pay_Period { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? Hours_per_Week { get; set; }

        public bool? Hazardous_Training { get; set; }

        public virtual Personal Personal { get; set; }
    }
}

Case Study 2/HRWebApp/HRWebApp/Controllers/JobHistoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HRWebApp.Models;

namespace HRWebApp.Controllers
{
    public class JobHistoryController : Controller
    {
        private HRDB db = new HRDB();

        // GET: JobHistory
        public ActionResult Index()
        {
            var job_History = db.Job_History.Include(j => j.Personal);
            return View(job_History.ToList());
        }

        // GET: JobHistory/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job_History job_History = db.Job_History.Find(id);
            if (job_History == null)
            {
                return HttpNotFound();
            }
            return View(job_History);
        }

        // GET: JobHistory/Create
        public ActionResult Create()
        {
            ViewBag.Employee_ID = new SelectList(db.Personals, "Employee_ID", "First_Name");
            return View();
        }

        // POST: JobHistory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Employee_ID,Department,Division,Start_Date,End_Date,Job_Title,Supervisor,Job_Category,Location,Departmen_Code,Salary_Type,Pay_Period,Hours_per_Week,Hazardous_Training")] Job_History job_History)
        {
            if (ModelState.IsValid)
            {
                db.Job_History.Add(job_History);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Employee_ID = new SelectList(db.Personals, "Employee_ID", "First_Name", job_History.Employee_ID);
            return View(job_History);
        }

        // GET: JobHistory/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job_History job_History = db.Job_History.Find(id);
            if (job_History == null)
            {
                return HttpNotFound();
            }
            ViewBag.Employee_ID = new SelectList(db.Personals, "Employee_ID", "First_Name", job_History.Employee_ID);
            return View(job_History);
        }

        // POST: JobHistory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Employee_ID,Department,Division,Start_Date,End_Date,Job_Title,Supervisor,Job_Category,Location,Departmen_Code,Salary_Type,Pay_Period,Hours_per_Week,Hazardous_Training")] Job_History job_History)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job_History).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Employee_ID = new SelectList(db.Personals, "Employee_ID", "First_Name", job_History.Employee_ID);
            return View(job_History);
        }

        // GET: JobHistory/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job_History job_History = db.Job_History.Find(id);
            if (job_History == null)
            {
                return HttpNotFound();
            }
            return View(job_History);
        }

        // POST: JobHistory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Job_History job_History = db.Job_History.Find(id);
            db.Job_History.Remove(job_History);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Case Study 2/HRWebApp/HRWebApp/Views/JobHistory/Create.cshtml
@model HRWebApp.Models.Job_History

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Job_History</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Employee_ID, "Employee_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Employee_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Employee_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Division, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Division, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Division, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.End_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Job_Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Job_Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Job_Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supervisor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supervisor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Supervisor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Job_Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Job_Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Job_Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departmen_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Departmen_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Departmen_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary_Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary_Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary_Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pay_Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pay_Period, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pay_Period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hours_per_Week, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hours_per_Week, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hours_per_Week, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hazardous_Training, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Hazardous_Training)
                    @Html.ValidationMessageFor(model => model.Hazardous_Training, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Case Study 2/HRWebApp/HRWebApp/Views/JobHistory/Delete.cshtml
@model HRWebApp.Models.Job_History

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job_History</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Personal.First_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personal.First_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Division)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Division)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job_Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job_Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supervisor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supervisor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job_Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job_Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departmen_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departmen_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pay_Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pay_Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hours_per_Week)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hours_per_Week)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hazardous_Training)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hazardous_Training)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Case Study 2/HRWebApp/HRWebApp/Views/JobHistory/Details.cshtml
@model HRWebApp.Models.Job_History

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Job_History</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Personal.First_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personal.First_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Division)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Division)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job_Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job_Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supervisor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supervisor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job_Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job_Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departmen_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departmen_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pay_Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pay_Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hours_per_Week)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hours_per_Week)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hazardous_Training)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hazardous_Training)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Case Study 2/HRWebApp/HRWebApp/Views/JobHistory/Edit.cshtml
@model HRWebApp.Models.Job_History

@{
    ViewBag.Title = "Edit";
}
<div class="content">
    <div class="module">
        <div class="module-head">
            <h3>Edit Job History</h3>
        </div>
        @using (Html.BeginForm("Edit", "JobHistory", FormMethod.Post, new { @class = "form-horizontal row-fluid" }))
        {
            @Html.AntiForgeryToken()
            <div class="module-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID)

                <div class="control-group">
                    @Html.LabelFor(model => model.Employee_ID, "Employee_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.DropDownList("Employee_ID", null, htmlAttributes: new { @class = "span6" })
                        @Html.ValidationMessageFor(model => model.Employee_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Division, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Division, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Division, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Start_Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Start_Date, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Start_Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.End_Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.End_Date, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.End_Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Job_Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Job_Title, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Job_Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Supervisor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Supervisor, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Supervisor, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Job_Category, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Job_Category, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Job_Category, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Departmen_Code, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Departmen_Code, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Departmen_Code, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Salary_Type, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Salary_Type, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Salary_Type, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Pay_Period, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Pay_Period, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Pay_Period, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Hours_per_Week, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Hours_per_Week, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Hours_per_Week, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Hazardous_Training, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Hazardous_Training)
                        @Html.ValidationMessageFor(model => model.Hazardous_Training, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    <div class="col-md-offset-2 controls">
                        <input type="submit" value="Save" class="btn btn-default" />
                        @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-default" })
                    </div>
                </div>
            </div>
        }
    </div>
</div><!--/.content-->

Case Study 2/HRWebApp/HRWebApp/Views/JobHistory/Index.cshtml
@model IEnumerable<HRWebApp.Models.Job_History>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Full Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Division)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Start_Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.End_Date)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Job_Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supervisor)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Job_Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Departmen_Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary_Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pay_Period)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hours_per_Week)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hazardous_Training)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Personal.First_Name)
            @Html.DisplayFor(modelItem => item.Personal.Last_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Division)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Start_Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.End_Date)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Job_Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supervisor)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Job_Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Departmen_Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary_Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pay_Period)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hours_per_Week)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hazardous_Training)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>