Case Study 2/HRWebApp/HRWebApp/HRWebApp/Models/Personal.cs
namespace HRWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Personal")]
    public partial class Personal
    {
        public Personal()
        {
            Job_History = new HashSet<Job_History>();
        }

        [Key]
        [Column(TypeName = "numeric")]
        public decimal Employee_ID { get; set; }

        [StringLength(50)]
        public string First_Name { get; set; }

        [StringLength(50)]
        public string Last_Name { get; set; }

        [StringLength(50)]
        public string Middle_Initial { get; set; }

        [StringLength(50)]
        public string Address1 { get; set; }

        [StringLength(50)]
        public string Address2 { get; set; }

        [StringLength(50)]
        public string City { get; set; }

        [StringLength(50)]
        public string State { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? Zip { get; set; }

        [StringLength(50)]
        public string Email { get; set; }

        [StringLength(50)]
        public string Phone_Number { get; set; }

        [StringLength(50)]
        public string Social_Security_Number { get; set; }

        [StringLength(50)]
        public string Drivers_License { get; set; }

        [StringLength(50)]
        public string Marital_Status { get; set; }

        public bool? Gender { get; set; }

        public bool Shareholder_Status { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? Benefit_Plans { get; set; }

        [StringLength(50)]
        public string Ethnicity { get; set; }

        public virtual Benefit_Plans Benefit_Plans1 { get; set; }

        public virtual Emergency_Contacts Emergency_Contacts { get; set; }

        public virtual Employment Employment { get; set; }

        public virtual ICollection<Job_History> Job_History { get; set; }
    }
}

Case Study 2/HRWebApp/HRWebApp/HRWebApp/Controllers/PersonalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HRWebApp.Models;

namespace HRWebApp.Controllers
{
    public class PersonalsController : Controller
    {
        private HRDB db = new HRDB();

        // GET: Personals
        public ActionResult Index()
        {
            var personals = db.Personals.Include(p => p.Benefit_Plans1).Include(p => p.Emergency_Contacts).Include(p => p.Employment);
            return View(personals.ToList());
        }

        // GET: Personals/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personal personal = db.Personals.Find(id);
            if (personal == null)
            {
                return HttpNotFound();
            }
            return View(personal);
        }

        // GET: Personals/Create
        public ActionResult Create()
        {
            ViewBag.Benefit_Plans = new SelectList(db.Benefit_Plans, "Benefit_Plan_ID", "Plan_Name");
            ViewBag.Employee_ID = new SelectList(db.Emergency_Contacts, "Employee_ID", "Emergency_Contact_Name");
            ViewBag.Employee_ID = new SelectList(db.Employments, "Employee_ID", "Employment_Status");
            return View();
        }

        // POST: Personals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Employee_ID,First_Name,Last_Name,Middle_Initial,Address1,Address2,City,State,Zip,Email,Phone_Number,Social_Security_Number,Drivers_License,Marital_Status,Gender,Shareholder_Status,Benefit_Plans,Ethnicity")] Personal personal)
        {
            if (ModelState.IsValid)
            {
                db.Personals.Add(personal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Benefit_Plans = new SelectList(db.Benefit_Plans, "Benefit_Plan_ID", "Plan_Name", personal.Benefit_Plans);
            ViewBag.Employee_ID = new SelectList(db.Emergency_Contacts, "Employee_ID", "Emergency_Contact_Name", personal.Employee_ID);
            ViewBag.Employee_ID = new SelectList(db.Employments, "Employee_ID", "Employment_Status", personal.Employee_ID);
            return View(personal);
        }

        // GET: Personals/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personal personal = db.Personals.Find(id);
            if (personal == null)
            {
                return HttpNotFound();
            }
            ViewBag.Benefit_Plans = new SelectList(db.Benefit_Plans, "Benefit_Plan_ID", "Plan_Name", personal.Benefit_Plans);
            ViewBag.Employee_ID = new SelectList(db.Emergency_Contacts, "Employee_ID", "Emergency_Contact_Name", personal.Employee_ID);
            ViewBag.Employee_ID = new SelectList(db.Employments, "Employee_ID", "Employment_Status", personal.Employee_ID);
            return View(personal);
        }

        // POST: Personals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Employee_ID,First_Name,Last_Name,Middle_Initial,Address1,Address2,City,State,Zip,Email,Phone_Number,Social_Security_Number,Drivers_License,Marital_Status,Gender,Shareholder_Status,Benefit_Plans,Ethnicity")] Personal personal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(personal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Benefit_Plans = new SelectList(db.Benefit_Plans, "Benefit_Plan_ID", "Plan_Name", personal.Benefit_Plans);
            ViewBag.Employee_ID = new SelectList(db.Emergency_Contacts, "Employee_ID", "Emergency_Contact_Name", personal.Employee_ID);
            ViewBag.Employee_ID = new SelectList(db.Employments, "Employee_ID", "Employment_Status", personal.Employee_ID);
            return View(personal);
        }

        // GET: Personals/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personal personal = db.Personals.Find(id);
            if (personal == null)
            {
                return HttpNotFound();
            }
            return View(personal);
        }

        // POST: Personals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Personal personal = db.Personals.Find(id);
            db.Personals.Remove(personal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Case Study 2/HRWebApp/HRWebApp/HRWebApp/Views/Personals/Create.cshtml
@model HRWebApp.Models.Personal

@{
    ViewBag.Title = "Create";
}
<div class="content">
    <div class="module">
        <div class="module-head">
            <h3>Create Personal</h3>
        </div>
        @using (Html.BeginForm("Create", "Personals", FormMethod.Post, new { @class = "form-horizontal row-fluid" }))
        {
            @Html.AntiForgeryToken()

            <div class="module-body">
                @*<form class="form-horizontal row-fluid">*@
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="control-group">
                    @*@Html.LabelFor(model => model.Employee_ID, htmlAttributes: new { @class = "control-label" })*@
                    <label class="control-label" for="EmployeeID">Employee ID</label>
                    <div class="controls">
                        @Html.EditorFor(model => model.Employee_ID, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Employee_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="EmployeeID">First Name</label>
                    <div class="controls">
                        @Html.EditorFor(model => model.First_Name, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.First_Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Last_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Last_Name, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Last_Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Middle_Initial, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Middle_Initial, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Middle_Initial, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Phone_Number, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Phone_Number, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Phone_Number, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Social_Security_Number, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Social_Security_Number, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Social_Security_Number, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Drivers_License, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Drivers_License, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Drivers_License, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Marital_Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Marital_Status, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Marital_Status, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.DropDownListFor(model => model.Gender, new List<SelectListItem> { new SelectListItem { Text = "Male", Value = "True" }, new SelectListItem { Text = "Female", Value = "False" } })
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Shareholder_Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                            @Html.EditorFor(model => model.Shareholder_Status)
                            @Html.ValidationMessageFor(model => model.Shareholder_Status, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Benefit_Plans, "Benefit_Plans", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.DropDownList("Benefit_Plans", null, htmlAttributes: new { @class = "span6" })
                        @Html.ValidationMessageFor(model => model.Benefit_Plans, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Ethnicity, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Ethnicity, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Ethnicity, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    <div class="col-md-offset-2 controls">
                        <input type="submit" value="Create" class="btn btn-default" />
                        @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-default" })

                    </div>
                </div>
                @*</form>*@
            </div>
        }
    </div>
</div><!--/.content-->

Case Study 2/HRWebApp/HRWebApp/HRWebApp/Views/Personals/Delete.cshtml
@model HRWebApp.Models.Personal

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Personal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Benefit_Plans1.Plan_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Benefit_Plans1.Plan_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Emergency_Contacts.Emergency_Contact_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Emergency_Contacts.Emergency_Contact_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employment.Employment_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employment.Employment_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.First_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.First_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Last_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Last_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Middle_Initial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Middle_Initial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Social_Security_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Social_Security_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Drivers_License)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Drivers_License)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marital_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marital_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shareholder_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shareholder_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ethnicity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ethnicity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Case Study 2/HRWebApp/HRWebApp/HRWebApp/Views/Personals/Edit.cshtml
@model HRWebApp.Models.Personal

@{
    ViewBag.Title = "Edit";
}
<div class="content">
    <div class="module">
        <div class="module-head">
            <h3>Edit Personal</h3>
        </div>
        @using (Html.BeginForm("Edit", "Personals", FormMethod.Post, new { @class = "form-horizontal row-fluid" }))
        {
            @Html.AntiForgeryToken()

            <div class="module-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Employee_ID)

                <div class="control-group">
                    @Html.LabelFor(model => model.First_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.First_Name, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.First_Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Last_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Last_Name, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Last_Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Middle_Initial, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Middle_Initial, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Middle_Initial, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Phone_Number, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Phone_Number, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Phone_Number, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Social_Security_Number, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Social_Security_Number, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Social_Security_Number, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Drivers_License, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Drivers_License, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Drivers_License, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Marital_Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Marital_Status, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Marital_Status, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.DropDownListFor(model => model.Gender, new List<SelectListItem> { new SelectListItem { Text = "Male", Value = "True" }, new SelectListItem { Text = "Female", Value = "False" } })
                        @*@Html.EditorFor(model => model.Gender)*@
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Shareholder_Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Shareholder_Status)
                        @Html.ValidationMessageFor(model => model.Shareholder_Status, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Benefit_Plans, "Benefit_Plans", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.DropDownList("Benefit_Plans", null, htmlAttributes: new { @class = "span6" })
                        @Html.ValidationMessageFor(model => model.Benefit_Plans, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.Ethnicity, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="controls">
                        @Html.EditorFor(model => model.Ethnicity, new { htmlAttributes = new { @class = "span6" } })
                        @Html.ValidationMessageFor(model => model.Ethnicity, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="control-group">
                    <div class="col-md-offset-2 controls">
                        <input type="submit" value="Save" class="btn btn-default" />
                        @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-default" })
                    </div>
                </div>
            </div>
        }
    </div>
</div><!--/.content-->